// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZziIdNkiBv97yeWMbKYZYElxo5dNx1c',
    appId: '1:822337344078:web:6b4f8c1b3800b797fe291f',
    messagingSenderId: '822337344078',
    projectId: 'sicklecare-15d7a',
    authDomain: 'sicklecare-15d7a.firebaseapp.com',
    storageBucket: 'sicklecare-15d7a.firebasestorage.app',
    measurementId: 'G-4F05CTPM31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb3hcEr6dOg-Yf8FKowBLUpc3uuF3rF8Q',
    appId: '1:822337344078:android:8eafbde452f270a3fe291f',
    messagingSenderId: '822337344078',
    projectId: 'sicklecare-15d7a',
    storageBucket: 'sicklecare-15d7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0T4zWM-9xidrV_N2-uJDJfBQQH-RI9c',
    appId: '1:822337344078:ios:29225294f57ab1fffe291f',
    messagingSenderId: '822337344078',
    projectId: 'sicklecare-15d7a',
    storageBucket: 'sicklecare-15d7a.firebasestorage.app',
    iosBundleId: 'com.example.sicklecareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC0T4zWM-9xidrV_N2-uJDJfBQQH-RI9c',
    appId: '1:822337344078:ios:29225294f57ab1fffe291f',
    messagingSenderId: '822337344078',
    projectId: 'sicklecare-15d7a',
    storageBucket: 'sicklecare-15d7a.firebasestorage.app',
    iosBundleId: 'com.example.sicklecareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3ZziIdNkiBv97yeWMbKYZYElxo5dNx1c',
    appId: '1:822337344078:web:bf96d817e5f96e94fe291f',
    messagingSenderId: '822337344078',
    projectId: 'sicklecare-15d7a',
    authDomain: 'sicklecare-15d7a.firebaseapp.com',
    storageBucket: 'sicklecare-15d7a.firebasestorage.app',
    measurementId: 'G-HQ856PJ8QF',
  );
}





